name: checking code

on:
  push

jobs:
  check_code:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: Linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: data-service

    - name: Install dependencies
      run: go mod download

    - name: Run Unit Tests
      run: go test -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Eeritvan/face_recognition